require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - .gems/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - lib/tasks/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config.ru
    - Guardfile
    - Rakefile
    - node_modules/**/*
    - app/queries/**/*
    - app/services/data_crawler_service.rb

Style/Encoding:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Style/InlineComment:
  Description: "Avoid inline comments."
  Enabled: false

Layout/LineLength:
  Description: "Limit lines to 100 characters. (Default is 80)"
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Security/Open:
  Exclude:
    - "app/services/data_crawler_service.rb"

Style/FrozenStringLiteralComment:
  Description: To help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false

Style/WordArray:
  Description: "Use %w or %W for arrays of words."
  Enabled: false

# Defaults all strings to double quotes. Less performant, but
# nicer for consistency, and for adding interpolation later.
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - "app/services/**/*"

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicateName:
  Enabled: false
# Prettier hashes.
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# No auto-correct for unused block arguments,
# but will still warn.
Lint/UnusedBlockArgument:
  AutoCorrect: false

# No auto-correct for unused method arguments,
# but will still warn.
Lint/UnusedMethodArgument:
  AutoCorrect: false

Rails/HasAndBelongsToMany:
  Enabled: false
