require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - .gems/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - lib/tasks/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config.ru
    - Guardfile
    - Rakefile
    - node_modules/**/*
    - app/queries/**/*
    - app/services/data_crawler_service.rb
Bundler/OrderedGems:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Layout/SpaceAroundOperators:
  EnforcedStyleForExponentOperator: space

Layout/LineLength:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - "app/services/**/*"

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/InlineComment:
  Description: "Avoid inline comments."
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Security/Open:
  Exclude:
    - "app/services/data_crawler_service.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/RedundantPercentQ:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 4

Metrics/BlockLength:
  Max: 65
  Exclude:
    - "spec/**/*"

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/MutableConstant:
  Enabled: true

Style/HashTransformValues:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/HashTransformKeys:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Lint/UnusedBlockArgument:
  AutoCorrect: false

Lint/UnusedMethodArgument:
  AutoCorrect: false

Lint/RescueException:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Output:
  Enabled: false
