databases:
  - name: taxcode
    databaseName: taxcode
    user: taxcode_user

services:
  - type: web
    name: taxcodeinfo
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taxcode
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
