:queues:
  - default
:scheduler:
  :schedule:
    crawl_province_monthly:
      cron: "0 0 1 * *"
      class: CrawlProvinceMonthlyWorker
    crawl_province_daily:
      cron: "0 0 * * *"
      class: CrawlProvinceWorker
